# Generated by Django 6.0.5 on 2026-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=150)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idade', models.PositiveIntegerField()),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
                ('prefere_saco_racao', models.BooleanField(verbose_name='Prefere comprar saco de ração?')),
                ('numero_pets', models.PositiveIntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
